/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2022-08-26 08:20:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.beer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/aischool/Desktop/work_folder/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/beer/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1661386272000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Beer</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\" />\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t\t.popup-wrap{\r\n");
      out.write("\t\t\t\tbackground-color:rgba(0,0,0,.3); \r\n");
      out.write("\t\t\t\tdisplay: flex;\r\n");
      out.write("\t\t\t\tflex-direction: column;\r\n");
      out.write("\t\t\t\tjustify-content:center;\r\n");
      out.write("\t\t\t\talign-items:center;\r\n");
      out.write("\t\t\t\tposition:fixed;\r\n");
      out.write("\t\t\t\ttop:0;\r\n");
      out.write("\t\t\t\tleft:0;\r\n");
      out.write("\t\t\t\tright:0;\r\n");
      out.write("\t\t\t\tbottom:0;\r\n");
      out.write("\t\t\t\tdisplay:none;  \r\n");
      out.write("\t\t\t\tz-index: 2;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"homepage is-preload\">\r\n");
      out.write("<script>\r\n");
      out.write("\t\t\tfunction open_popup(){\r\n");
      out.write("\t\t\t\tvar log_popup = document.getElementById(\"popup\")\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tconsole.log(log_popup);\r\n");
      out.write("\t\t\t\tlog_popup.style.display=\"flex\"\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction close_popup(){\r\n");
      out.write("\t\t\t\tvar log_popup = document.getElementById(\"popup\")\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tconsole.log(log_popup);\r\n");
      out.write("\t\t\t\tlog_popup.style.display=\"none\"\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<span style=\"display: none;\"></span>\r\n");
      out.write("\t\t<div id=\"popup\" class=\"popup-wrap\" style=\"width: 100%;height: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"width: 450px;height: 350px; background-color: #fff;border-radius: 15px 15px 0 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width: 100%;height: 70px;background-color: #d52349;padding: 15px;border-radius: 15px 15px 0 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2 style=\"color: white; margin-top: 10px;\">로그인</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"width: 100%;height: 300px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.pik\" method=\"post\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\" style=\"justify-content: center;height: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-4 col-6-medium col-12-small \" style=\"width: 85%; margin-top:20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- 아이디 입력 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"join_title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"m_id\">ID</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"padding: 0; display: flex;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"m_id\" name=\"m_id\" class=\"int\" title=\"ID\" placeholder=\"아이디를 입력하세요\" maxlength=\"20\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- 비밀번호 입력 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"join_title\" style=\"margin-top: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"m_pw\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"box\" style=\"padding: 0; border-color: #fff;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" id=\"m_pw\" name=\"m_pw\" class=\"int\" placeholder=\"비밀번호를 입력하세요\" title=\"비밀번호 입력\" aria-describedby=\"pswd1Msg\" maxlength=\"20\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"actions\"  style=\"margin-top: 35px; width: 100%;height: 20%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input style=\" font-size: 1.3em;width: 50%;height: 100%;margin: 0;float: left;border-radius: 0 0 0 15px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"submit\" class=\"button\" value=\"로그인\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input style=\" font-size: 1.3em;width: 50%;height: 100%;margin:0;float: right;border-radius: 0 0 15px 0;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype=\"button\" onclick=\"close_popup()\" class=\"button alt\" value=\"취소\"id=\"login-cancel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input style=\"clear: both;\" hidden>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<div style=\"position: fixed; top: 10%; right: 2%;z-index: 1;\">\r\n");
      out.write("\t\t\t<button onclick=\"open_popup()\">login</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<span style=\"display: none;\"></span>\r\n");
      out.write("\t<!-- Scripts -->\r\n");
      out.write("\t<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/util.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/beer/login.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      // /WEB-INF/beer/login.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/beer/login.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
