/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2022-09-05 11:26:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.beer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.entity.pik.Member;
import kr.entity.pik.Paging;
import java.io.PrintWriter;
import org.apache.ibatis.reflection.SystemMetaObject;
import kr.entity.pik.Member;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/aischool/Desktop/work_folder/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/beer/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/beer/footer.jsp", Long.valueOf(1662360207153L));
    _jspx_dependants.put("/WEB-INF/beer/login.jsp", Long.valueOf(1662374292769L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1662076816000L));
    _jspx_dependants.put("/WEB-INF/beer/nav.jsp", Long.valueOf(1662373504685L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("org.apache.ibatis.reflection.SystemMetaObject");
    _jspx_imports_classes.add("kr.entity.pik.Paging");
    _jspx_imports_classes.add("kr.entity.pik.Member");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Beer</title>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\" />\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#main_beer_info{\t\r\n");
      out.write("\t\t\toverflow:hidden;\t\t\t\r\n");
      out.write("\t\t\tdisplay:none;\r\n");
      out.write("\t\t\tposition:absolute;\r\n");
      out.write("\t\t\ttop:150px;\r\n");
      out.write("\t\t\tleft:120px;\r\n");
      out.write("\t\t\twidth:1300px;\r\n");
      out.write("\t\t\theight:670px;\r\n");
      out.write("\t\t\tz-index:1;\t\t\t\r\n");
      out.write("\t\t\tborder: 3px solid beige; \r\n");
      out.write("\t\t\tborder-radius: 35%; \r\n");
      out.write("\t\t\t-moz-border-radius: 35%; \r\n");
      out.write("\t\t\t-khtml-border-radius: 35%; \r\n");
      out.write("\t\t\t-webkit-border-radius: 35%;\r\n");
      out.write("\t\t\tmargin:auto;\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#main_beer_info_back{\r\n");
      out.write("\t\t\tdisplay:none;\r\n");
      out.write("\t\t\tbackground-color: black;\r\n");
      out.write("\t\t\tposition:absolute;\r\n");
      out.write("\t\t\ttop:150px;\r\n");
      out.write("\t\t\tleft:120px;\r\n");
      out.write("\t\t\twidth:1300px;\r\n");
      out.write("\t\t\theight:670px;\r\n");
      out.write("\t\t\tz-index:1;\t\r\n");
      out.write("\t\t\topacity: 0.8;\r\n");
      out.write("\t\t\tborder: 3px solid beige; \r\n");
      out.write("\t\t\tborder-radius: 35%; \r\n");
      out.write("\t\t\t-moz-border-radius: 35%; \r\n");
      out.write("\t\t\t-khtml-border-radius: 35%; \r\n");
      out.write("\t\t\t-webkit-border-radius: 35%;\r\n");
      out.write("\t\t\tmargin:auto;\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#main_beer_table{\t\t\t\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tjustify-content:center;\t\r\n");
      out.write("\t\t\tvertical-align:middle;\r\n");
      out.write("\t\t\tposition:absolute;\r\n");
      out.write("\t\t\tleft:200px;\r\n");
      out.write("\t\t\ttop:80px; \r\n");
      out.write("\t\t\tmargin:auto;\t\t\t\t\t\r\n");
      out.write("\t\t\tborder: 3px solid #606060;\r\n");
      out.write("\t\t\twidth: 70%;\r\n");
      out.write("\t\t\theight: 50%;\r\n");
      out.write("\t\t\ttable-layout: fixed;\r\n");
      out.write("\t\t\tz-index: 2;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#main_beer_table tr{\r\n");
      out.write("\t\t\tdisplay:flex;\t\t\t\r\n");
      out.write("\t\t\tmargin:auto;\r\n");
      out.write("\t\t\tjustify-content:center;\t\t\t\r\n");
      out.write("\t\t\ttext-align: center; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#main_beer_table td{\t\t\r\n");
      out.write("\t\t\tdisplay:flex;\t\t\t\t\r\n");
      out.write("\t\t\tmargin:auto;\t\t\r\n");
      out.write("\t\t\tjustify-content:center;\t\t\r\n");
      out.write("\t\t\ttext-align: center;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#main_beer_table h2,h3{\r\n");
      out.write("\t\t\tcolor:beige !important;\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\t\r\n");
      out.write("\t\t$(document).ready(function(){\t\t\t\r\n");
      out.write("\t\t\t$(\"#home_btn\").addClass(\"current\");\t\t\t\t\r\n");
      out.write("\t\t\tinitMap\r\n");
      out.write("\t\t}) \t\t\r\n");
      out.write("\t\t$(function () {\r\n");
      out.write("\t\t\t$(\"#main_img\").click(()=>{\r\n");
      out.write("\t\t\t\t$(\"#intro\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t$(\"#banner\").css(\"display\",\"block\");\t\t\t\t\r\n");
      out.write("\t\t\t})\t\r\n");
      out.write("\t\t\t$(\"#main_logo1\").click(()=>{\r\n");
      out.write("\t\t\t\t$(\"#intro\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t\t$(\"#banner\").css(\"display\",\"block\");\t\r\n");
      out.write("\t\t\t})\t\r\n");
      out.write("\t\t})\t\t\t\r\n");
      out.write("\t\tfunction goLogIn(){\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/loginForm.pik\"\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\tfunction goLogOut(){\r\n");
      out.write("\t\t\t if (confirm(\"정말 삭제하시겠습니까??\") == true){\r\n");
      out.write("\t\t\t\t location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout.pik\"\r\n");
      out.write("\t\t\t }else{ \r\n");
      out.write("\t\t\t     return false;\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"homepage is-preload\">\r\n");
      out.write("\t<div id=\"page-wrapper\">\t\t\r\n");
      out.write("\t\t<!-- Header -->\r\n");
      out.write("\t\t<section id=\"header\" style=\"padding-top: 0; padding-bottom: 0;\">\r\n");
      out.write("\t\t\t<!-- Nav -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Beer</title>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\" />\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var loginID = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.m_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("        \r\n");
      out.write("         $(function(){\r\n");
      out.write("             if(loginID){\r\n");
      out.write("                 $(\"#loginMember\").css(\"display\",\"inline-block\");\r\n");
      out.write("             }else{\r\n");
      out.write("                 $(\"#loginMember\").css(\"display\",\"none\");\r\n");
      out.write("             }\r\n");
      out.write("         });\r\n");
      out.write("         $(document).ready(function(){      \r\n");
      out.write("                ");
String btnPath = request.getRequestURI().split("/")[4].split("\\.")[0];
                if(btnPath.indexOf("articleList")!=-1 || btnPath.indexOf("articleView")!=-1){
                
      out.write("$(\"#review_btn\").addClass(\"current\");  ");

                }else if(btnPath.indexOf("eventList")!=-1){
                
      out.write("$(\"#notice_btn\").addClass(\"current\");  ");

                }else if(btnPath.indexOf("myPage")!=-1){
                
      out.write("$(\"#loginMember\").addClass(\"current\"); ");

                }
      out.write("\r\n");
      out.write("            })  \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    .a-hover:hover {\r\n");
      out.write("    \tbackground-color: rgba(255, 217, 0, 0.232) !important;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Logo -->\r\n");
      out.write("<div style=\"background-color:#252122; height:200px;\">\r\n");
      out.write("    <h1 style=\"padding-top: 45px\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.pik\" style=\"color:gold\">Beer</a></h1>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!-- Nav -->\r\n");
      out.write("    <nav id=\"nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li id=\"home_btn\"><a class=\"a-hover\" style=\"color:#f7f7f7;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.pik\">Home</a></li>\r\n");
      out.write("            <li id=\"info_btn\"><a class=\"a-hover\" style=\"color:#f7f7f7;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/beerRecommendForm.pik\">Beer Info</a></li>\r\n");
      out.write("            <li id=\"search_btn\"><a class=\"a-hover\" style=\"color:#f7f7f7;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/beerSearchForm.pik\">Beer Search</a></li>\r\n");
      out.write("            <li id=\"review_btn\"><a class=\"a-hover\" style=\"color:#f7f7f7;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/articleList.pik?page=1\">Review</a></li>\r\n");
      out.write("            <li id=\"notice_btn\"><a class=\"a-hover\" style=\"color:#f7f7f7;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/eventList.pik\">Notice</a></li>\r\n");
      out.write("            <li id=\"loginMember\"><a class=\"a-hover\" style=\"color:#f7f7f7;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage.pik\">My Page</a></li>\r\n");
      out.write("            \r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Beer</title>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\"\r\n");
      out.write("\t\tcontent=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\" />\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t\t.popup-wrap{\r\n");
      out.write("\t\t\t\tbackground-color:rgba(0,0,0,.3);\r\n");
      out.write("\t\t\t\tdisplay: flex;\r\n");
      out.write("\t\t\t\tflex-direction: column;\r\n");
      out.write("\t\t\t\tjustify-content:center;\r\n");
      out.write("\t\t\t\talign-items:center;\r\n");
      out.write("\t\t\t\tposition:fixed;\r\n");
      out.write("\t\t\t\ttop:0;\r\n");
      out.write("\t\t\t\tleft:0;\r\n");
      out.write("\t\t\t\tright:0;\r\n");
      out.write("\t\t\t\tbottom:0;\r\n");
      out.write("\t\t\t\tz-index: 2;\r\n");
      out.write("\t\t\t\tdisplay:none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tif (!\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"){\r\n");
      out.write("\t\t\t$(\"#logInBtn\").css(\"display\",\"flex\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#logOutBtn\").css(\"display\",\"flex\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"homepage is-preload\">\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t");
 String reqPath = request.getRequestURI().split("/")[4].split("\\.")[0]+".pik";
		if(reqPath.indexOf("articleList")!=-1){
			reqPath+="?page=1";
		}else if(reqPath.indexOf("main")!=-1){
			reqPath="index.pik";
		}else if(reqPath.indexOf("info")!=-1){
			reqPath="beerRecommendForm.pik";
		}else if(reqPath.indexOf("search")!=-1){
			reqPath="beerSearchForm.pik";
		}else if(reqPath.indexOf("articleView")!=-1){
			String b_seq = request.getParameter("b_seq");
			reqPath+="?b_seq="+b_seq;
		}else if(reqPath.indexOf("myPage") != -1) {
			reqPath="index.pik";
		}
		
		
      out.write("\r\n");
      out.write("\t\tfunction open_popup(){\r\n");
      out.write("\t\t\tvar log_popup = document.getElementById(\"popup\")\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\tlog_popup.style.display=\"flex\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction log_out(){\r\n");
      out.write("\t\t\t if (confirm(\"정말 로그아웃 하시겠습니까?\") == true){\r\n");
      out.write("\t\t\t     location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout.pik?reqPath=");
      out.print(reqPath);
      out.write("\"\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t }else{\r\n");
      out.write("\t\t\t     return false;\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction close_popup(){\r\n");
      out.write("\t\t\tvar log_popup = document.getElementById(\"popup\")\r\n");
      out.write("\t\t\tlog_popup.style.display=\"none\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction login_submit(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar fData= $(\"#loginForm\").serialize();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.pik\",\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdata : fData,\r\n");
      out.write("\t\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\t\tlet data = $.trim(result)\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(data===\"aa\"){\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\tgoMain();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#failMsg\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(){alert(\"error\");} \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction goMain(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"+\"");
      out.print(reqPath);
      out.write("\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"logInBtn\" style=\"display:none; position: absolute; top: 5%; right: 2%;z-index: 2;  \">\r\n");
      out.write("\t\t<button onclick=\"open_popup()\" >LogIn</button>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"logOutBtn\" style=\"display:none; position: absolute; top: 5%; right: 2%;z-index: 2;\">\r\n");
      out.write("\t\t<button class=\"alt\" style=\"border:solid 1px #F2CB05; background-color: none; color:#F2CB05 !important;\" onclick=\"log_out()\">LogOut</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"popup\" class=\"popup-wrap\" style=\"width: 100%;height: 100%;\">\r\n");
      out.write("\t\t<div style=\"width: 450px;height: auto; background-color: #fff; border-radius: 15px 15px 15px 15px;\">\r\n");
      out.write("\t\t\t<div style=\"width: 100%;height: auto;background-color: #D52349;padding: 15px;border-radius: 15px 15px 0 0;\">\r\n");
      out.write("\t\t\t\t<div style=\"margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"color: white; margin-top: 10px;\">로그인</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"width: 100%;height: auto;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form id=\"loginForm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\" style=\"justify-content: center;height: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-4 col-6-medium col-12-small \" style=\"width: 85%; margin-top:20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 아이디 입력 -->\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"join_title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"m_id\">ID</label>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"padding: 0; display: flex;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"m_id\" name=\"m_id\" class=\"int\" title=\"ID\" placeholder=\"아이디를 입력하세요\" maxlength=\"20\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 비밀번호 입력 -->\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"join_title\" style=\"margin-top: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"m_pw\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box\" style=\"padding: 0; border-color: #fff;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" id=\"m_pw\" name=\"m_pw\" class=\"int\" placeholder=\"비밀번호를 입력하세요\" title=\"비밀번호 입력\" aria-describedby=\"pswd1Msg\" maxlength=\"20\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"failMsg\" class=\"box\" style=\"display:none;margin-top:10px;padding: 0 0 0 0; border-color: #fff;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"color:red; font : bold;\">아이디와 비밀번호를 확인하세요</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box\" style=\"margin-top:10px;padding: 0 0 0 0; border-color: #fff;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/registerForm.pik\" style=\"color:blue; text-decoration-line: none !important; color: #5D5D5D;\">아직 회원이 아니시라면? 회원가입</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input hidden value=\"");
      out.print(reqPath);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"actions\"  style=\"margin-top: 25px; width: 100%;height: 20%;\">\r\n");
      out.write("\t\t\t\t\t\t<input style=\" font-size: 1.3em;width: 50%;height: 100%;margin: 0;float: left;border-radius: 0 0 0 15px;\"\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"button\" onclick=\"login_submit()\" class=\"button\" value=\"로그인\">\r\n");
      out.write("\t\t\t\t\t\t<input style=\" font-size: 1.3em;width: 50%;height: 100%;margin:0;float: right;border-radius: 0 0 15px 0;\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" onclick=\"close_popup()\" class=\"button alt\" value=\"취소\"id=\"login-cancel\">\r\n");
      out.write("\t\t\t\t\t\t<input style=\"clear: both;\" hidden>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Scripts -->\r\n");
      out.write("\t<script type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/util.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!-- Banner -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<section id=\"banner\" style=\"display: none; width:100%; background-color:#f7f7f7; margin:0; padding:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div><header>\r\n");
      out.write("\t\t\t\t\t<h2 style=\"color:red;\">World Beer</h2>\r\n");
      out.write("\t\t\t\t</header></div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"main_beer_info_back\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"main_beer_info\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"map\" style=\" margin: auto; width:80%; height: 90vh; border: 3px solid beige; border-radius: 35%; -moz-border-radius: 35%; -khtml-border-radius: 35%; -webkit-border-radius: 35%;\" ></div>\r\n");
      out.write("\t\t\t\t<script async defer src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyAbBcCMNhGYduCOpd6vUqXX1yiiKtFBCKM&callback=initMap&region=kr\"></script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<button id=\"NA_btn\">N_America</button>\r\n");
      out.write("\t\t\t\t<button id=\"SA_btn\">S_America</button>\r\n");
      out.write("\t\t\t\t<button id=\"Home_btn\">Home</button>\r\n");
      out.write("\t\t\t\t<button id=\"OC_btn\">Oceania</button>\r\n");
      out.write("\t\t\t\t<button id=\"Asia_btn\">Asia</button>\r\n");
      out.write("\t\t\t\t<button id=\"EU_btn\">EU</button>\r\n");
      out.write("\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\tvar json;\t\t\t\r\n");
      out.write("\t\t\t\t\tvar map;\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfunction initMap() {\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t      \tvar seoul = { lat: 22 ,lng: 155 };\r\n");
      out.write("\t\t\t\t\t      \t   map = new google.maps.Map(\r\n");
      out.write("\t\t\t\t\t           document.getElementById('map'), {\r\n");
      out.write("\t\t\t\t\t           mapId: \"67040d7b26feccd0\",\r\n");
      out.write("\t\t\t\t\t           zoom: 2.5,\r\n");
      out.write("\t\t\t\t\t           center: seoul,\r\n");
      out.write("\t\t\t\t\t           scaleControl: false,\r\n");
      out.write("\t\t\t\t\t           zoomControl: false,\r\n");
      out.write("\t\t\t\t\t           disableDefaultUI: true,\r\n");
      out.write("\t\t\t\t\t           scrollwheel:false\t\t\t\t\t           \r\n");
      out.write("\t\t\t\t\t        });\t\t\t\t\t\t\t      \t\r\n");
      out.write("\t\t\t\t      \t\tvar beer_icon = {\r\n");
      out.write("\t\t\t\t\t  \t  \t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/beer_icon.png\",\r\n");
      out.write("\t\t\t\t\t  \t  \t \tsize: new google.maps.Size(30, 30),\r\n");
      out.write("\t\t\t\t\t  \t      \torigin: new google.maps.Point(0, 0),\r\n");
      out.write("\t\t\t\t\t  \t     \tanchor: new google.maps.Point(20, 40),\r\n");
      out.write("\t\t\t\t\t  \t      \tscaledSize: new google.maps.Size(30, 30),\t\t\t  \t  \t\r\n");
      out.write("\t\t\t\t\t  \t  \t}; \t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t      \tvar location = [\t\r\n");
      out.write("\t\t\t\t\t    \t  \t['한국 : 서울', 36, 127, 'c25'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['프랑스 : 파리', 48.859737, 2.286952, 'c21'],\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t['미국 : 네바다', 36.070672, -114.774761, 'c6'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['벨기에 : 브뤼셀', 50.852055, 4.410520, 'c7'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['네덜란드 : 암스테르담', 52.326281, 4.952734, 'c1'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['핀란드 : 헬싱키', 60.186836, 24.932017, 'c22'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['인도네시아 : 마카사르', -5.151862, 119.569696, 'c14'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['스페인 : 마드리드', 40.315160, -3.642962, 'c9'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['아일랜드 : 더블린', 53.335206, -6.275992, 'c12'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['리투아니아 : 빌뉴스', 54.679764, 25.209341, 'c4'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['캐나다 : 오타와', 45.397979, -75.839435, 'c19'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['사이프러스 : 키프로스', 35.016122, 33.246252, 'c8'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['필리핀 : 마닐라', 14.580284, 120.989074, 'c23'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['일본 : 도쿄', 35.682199, 139.733488, 'c15'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['독일 : 베를린', 52.513671, 13.424698, 'c3'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['싱가포르', 1.350042, 103.866935, 'c10'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['오스트리아', 47.511629, 14.139651, 'c13'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['중국 : 베이징', 39.897541, 116.375205, 'c17'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['덴마크 : 쾨벤하운', 55.665090, 12.561425, 'c2'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['미국 : 하와이', 21.301016, -157.800359, 'c24'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['멕시코 : 멕시코시티', 19.383294, -99.131366, 'c5'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['체코 : 프라하', 50.057786, 14.444190, 'c18'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['아르헨티나 : 부에노스아이레스', -34.674657, -58.488043, 'c11'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['잉글랜드 : 버밍엄', 52.447896, -1.861060, 'c16'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['호주 : 멜버른', -37.824746, 145.090334, 'c26'],\r\n");
      out.write("\t\t\t\t\t\t\t\t['태국 : 방콕', 13.728943, 100.558400, 'c20']\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t];\r\n");
      out.write("\t\t\t\t\t      \t\r\n");
      out.write("\t\t\t\t\t    \t//인포윈도우\r\n");
      out.write("\t\t\t\t            var infowindow = new google.maps.InfoWindow();\t\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t  \t  \tvar marker, i;\t\t\t\t\t  \t  \t\t\t\t  \t  \r\n");
      out.write("\t\t\t\t\t  \t  \t\r\n");
      out.write("\t\t\t\t\t  \t  \tfor (var i=0; i < location.length; i++){\r\n");
      out.write("\t\t\t\t\t\t\t\tmarker = new google.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\t\t\t\ticon : beer_icon,\r\n");
      out.write("\t\t\t\t\t\t\t  \t    position: { lat: location[i][1] ,lng: location[i][2] },\r\n");
      out.write("\t\t\t\t\t\t\t  \t    map: map,\r\n");
      out.write("\t\t\t\t\t\t\t  \t    label: location[i][0]\r\n");
      out.write("\t\t\t\t\t  \t  \t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tgoogle.maps.event.addListener(marker, 'click', (function(marker, i) {\r\n");
      out.write("\t\t\t\t                    return function() {\t\t\t\t\t                    \t\r\n");
      out.write("\t\t\t\t                    \t$(\"#main_beer_info\").css('display', 'block');\r\n");
      out.write("\t\t\t\t                    \t$(\"#main_beer_info_back\").css('display', 'block');\t\t\t\t                    \t\r\n");
      out.write("\t\t\t\t                        //html로 표시될 인포 윈도우의 내용\r\n");
      out.write("\t\t\t\t                        //infowindow.setContent(location[i][0]);\r\n");
      out.write("\t\t\t\t                        \r\n");
      out.write("\t\t\t\t                        //인포윈도우가 표시될 위치\r\n");
      out.write("\t\t\t\t                        //infowindow.open(map, marker);\t\t\t\t                        \r\n");
      out.write("\t\t\t\t                    \t$.ajax({\r\n");
      out.write("\t\t\t\t                    \t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/beerCountyList.pik',\r\n");
      out.write("\t\t\t\t                    \t\ttype:\"get\",\r\n");
      out.write("\t\t\t\t                    \t\tdata:{\"country\":location[i][3]},\r\n");
      out.write("\t\t\t\t                    \t\tsuccess: function(res){\r\n");
      out.write("\t\t\t\t                    \t\t\tjson = res;\r\n");
      out.write("\t\t\t\t                    \t\t\tcountry(res, 1);\r\n");
      out.write("\t\t\t\t                    \t\t},\r\n");
      out.write("\t\t\t\t                    \t\terror: function () {alert(\"Error!!\")}\t\t\t\t                    \t\t\r\n");
      out.write("\t\t\t\t                    \t})\t\t\r\n");
      out.write("\t\t\t\t                    }\r\n");
      out.write("\t\t\t\t                })(marker, i));\t\t\t\t                \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t                if (marker) {\r\n");
      out.write("\t\t\t\t                    marker.addListener('click', function() {\t\t\t\t                        \r\n");
      out.write("\t\t\t\t                        //중심 위치를 클릭된 마커의 위치로 변경\r\n");
      out.write("\t\t\t\t                        map.setCenter(this.getPosition());\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t                        //마커 클릭 시의 줌 변화\r\n");
      out.write("\t\t\t\t                        map.setZoom(11);\r\n");
      out.write("\t\t\t\t                    });\r\n");
      out.write("\t\t\t\t                }\t\t\t\t                \r\n");
      out.write("\t\t\t\t\t  \t  \t};\t\t\t\t\t\t  \t  \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t  \t  \r\n");
      out.write("\t\t\t\t\tfunction country (data, page) {\r\n");
      out.write("\t\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t\t  \t\t// 3개 단위로 페이징\t\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t\t  \t\tvar html=\"\";\r\n");
      out.write("\t\t\t\t\t  \t\tvar max = 3;\r\n");
      out.write("\t\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t\t  \t\thtml += \"<table id='main_beer_table'>\";\r\n");
      out.write("\t\t\t\t\t  \t\tfor(let i = (page - 1)*3; i < (max*page > data.length ? data.length : max * page); i++){\r\n");
      out.write("\t\t\t\t\t  \t\t\tvar beer = data[i]\t\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\thtml += \"<tr>\";\r\n");
      out.write("\t\t\t\t\t  \t\t\thtml += \"<td ><img src='\"+beer.BEER_SRC+\"'style='width:150px; height:150px;'></td>\";\r\n");
      out.write("\t\t\t\t\t  \t\t\thtml += \"<td style='width:500px;'><h2>\"+beer.BEER_NAME+\"</h2></td>\";\r\n");
      out.write("\t\t\t\t\t  \t\t\thtml += \"<td style='width:200px;'><h3>\"+beer.AROMA_SEQ+\"</h3></td>\";\t\t\t\t\t  \t\t\t\t\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\tif (beer.TASTE_SEQ3 != null){\r\n");
      out.write("\t\t\t\t\t  \t\t\t\thtml += \"<td style='width:200px;'><h3>\"+beer.TASTE_SEQ+\"/\"+beer.TASTE_SEQ2+\"/\"+beer.TASTE_SEQ3+\"</h3></td>\";\r\n");
      out.write("\t\t\t\t\t  \t\t\t} else {\r\n");
      out.write("\t\t\t\t\t  \t\t\t\thtml += \"<td style='width:250px;'><h3>\"+beer.TASTE_SEQ+\"/\"+beer.TASTE_SEQ2+\"</h3></td>\";\r\n");
      out.write("\t\t\t\t\t  \t\t\t}\t\t\t\t\t  \t\t\t\t\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\thtml += \"</tr>\";\t\r\n");
      out.write("\t\t\t\t\t  \t\t}\t\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t\t  \t\thtml += \"</table>\";\t\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t\t  \t\tvar start = 1;\r\n");
      out.write("\t\t\t\t\t  \t\tvar end = 5;\r\n");
      out.write("\t\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t\t  \t\tvar n = 0;\r\n");
      out.write("\t\t\t\t  \t\t\tif(data.length%max == 0){\r\n");
      out.write("\t\t\t\t  \t\t\t\tn = parseInt(data.length/max);\r\n");
      out.write("\t\t\t\t  \t\t\t}else{\r\n");
      out.write("\t\t\t\t  \t\t\t\tn = parseInt(data.length/max) + 1;\r\n");
      out.write("\t\t\t\t  \t\t\t}\r\n");
      out.write("\t\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t  \t\t\tif(n>5){\r\n");
      out.write("\t\t\t\t\t\t  \t\tif(page > 3){\r\n");
      out.write("\t\t\t\t\t\t  \t\t\tif(page <= n - 2){\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\tstart = page - 2;\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\tend = page + 2;\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\tstart = n - 4;\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\tend = n\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t}\r\n");
      out.write("\t\t\t\t\t\t  \t\t}\r\n");
      out.write("\t\t\t\t  \t\t\t}else{\r\n");
      out.write("\t\t\t\t  \t\t\t\tend = n;\r\n");
      out.write("\t\t\t\t  \t\t\t}\r\n");
      out.write("\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\thtml += \"<br>\";\r\n");
      out.write("\t\t\t\t\t  \t\tfor(let i = start ; i <= end; i++ ){\r\n");
      out.write("\t\t\t\t\t  \t\t\tif( i == page){\r\n");
      out.write("\t\t\t\t\t\t\t  \t\thtml += \"<a style='font-size:30px; font-weigh:bold; color : white;' href='javascript:country(json, \" + i + \")'>\" + i + \"</a> &nbsp\"\r\n");
      out.write("\t\t\t\t\t  \t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t  \t\thtml += \"<a style='font-size:20px; font-weigh:bold; color : beige;' href='javascript:country(json, \" + i + \")'>\" + i + \"</a> &nbsp\"\t\t\t\t\t  \t\t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t}\r\n");
      out.write("\t\t\t\t\t  \t\t}\t\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t\t  \t\t$(\"#main_beer_info\").html(html);\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t\t  \t  }\t \t  \r\n");
      out.write("\t\t\t\t\t  \t  \t\r\n");
      out.write("\t\t\t\t\t  \t  function change_NA () {\r\n");
      out.write("\t\t\t\t\t  \t\tvar NA = { lat: 33.59, lng: -103.44 };\r\n");
      out.write("\t\t\t\t\t  \t\t  map.panTo(NA);\r\n");
      out.write("\t\t\t\t\t  \t\t  map.setZoom(4);\t\r\n");
      out.write("\t\t\t\t\t\t  }\t\t\t  \t  \r\n");
      out.write("\t\t\t\t\t  \t  function change_SA () {\r\n");
      out.write("\t\t\t\t\t  \t\tvar SA = { lat: -34.36, lng: -60.54 };\r\n");
      out.write("\t\t\t\t\t  \t\t  map.panTo(SA);\r\n");
      out.write("\t\t\t\t\t  \t\t  map.setZoom(4);\t\r\n");
      out.write("\t\t\t\t\t  \t  }\t\t\t  \t  \r\n");
      out.write("\t\t\t\t\t  \t  function change_OC () {\r\n");
      out.write("\t\t\t\t\t  \t\tvar OC = { lat: -10.77, lng: 121.16 };\r\n");
      out.write("\t\t\t\t\t  \t\t  map.panTo(OC);\r\n");
      out.write("\t\t\t\t\t  \t\t  map.setZoom(4);\t\r\n");
      out.write("\t\t\t\t\t  \t  }\r\n");
      out.write("\t\t\t\t\t  \t  function change_Asia () {\r\n");
      out.write("\t\t\t\t\t  \t\tvar Asia = { lat: 35.50, lng: 117.34 };\r\n");
      out.write("\t\t\t\t\t  \t\t  map.panTo(Asia);\r\n");
      out.write("\t\t\t\t\t  \t\t  map.setZoom(4);\t\r\n");
      out.write("\t\t\t\t\t  \t  }\r\n");
      out.write("\t\t\t\t\t  \t  function change_EU () {\r\n");
      out.write("\t\t\t\t\t  \t\tvar EU = { lat: 48.46, lng: 3.43 };\r\n");
      out.write("\t\t\t\t\t  \t\t  map.panTo(EU);\r\n");
      out.write("\t\t\t\t\t  \t\t  map.setZoom(4);\t\r\n");
      out.write("\t\t\t\t\t  \t  }\r\n");
      out.write("\t\t\t\t\t  \t  function change_home () {\r\n");
      out.write("\t\t\t\t\t  \t\tvar home = { lat: 22, lng: 155 };\r\n");
      out.write("\t\t\t\t\t  \t\t  map.panTo(home);\r\n");
      out.write("\t\t\t\t\t  \t\t  map.setZoom(2.5);\t\r\n");
      out.write("\t\t\t\t\t  \t\t  infowindow.close();\r\n");
      out.write("\t\t\t\t\t  \t  }\r\n");
      out.write("\t\t\t\t\t  \t  \r\n");
      out.write("\t\t\t\t\t  \t  $(function () {\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t$(\"#NA_btn\").click(function () {\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\tchange_NA();\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t})\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t$(\"#SA_btn\").click(function () {\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\tchange_SA();\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t})\r\n");
      out.write("\t\t\t\t\t  \t\t\t$(\"#OC_btn\").click(function () {\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\tchange_OC();\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t})\r\n");
      out.write("\t\t\t\t\t  \t\t\t$(\"#Asia_btn\").click(function () {\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\tchange_Asia();\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t})\r\n");
      out.write("\t\t\t\t\t  \t\t\t$(\"#EU_btn\").click(function () {\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\tchange_EU();\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t})\r\n");
      out.write("\t\t\t\t\t  \t\t\t$(\"#Home_btn\").click(function () {\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t$(\"#main_beer_info\").css('display', 'none');\r\n");
      out.write("\t\t\t\t\t\t  \t\t\t$(\"#main_beer_info_back\").css('display', 'none');\r\n");
      out.write("\t\t\t\t\t\t  \t\t\tchange_home();\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t})\r\n");
      out.write("\t\t\t\t\t  \t  })\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t</section>\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- Intro -->\r\n");
      out.write("\t\t\t<section id=\"intro\" class=\"container\">\r\n");
      out.write("\t\t\t\t<div id=\"main_img_div\" >\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <h2 style=\"color:gold;\"> 세계 맥주를 보고 싶으신가요? </h2> -->\r\n");
      out.write("\t\t\t\t\t<div style=\"position:absolute; top:250px; left:800px\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><img id=\"main_logo1\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/main_font_logo1.png\" alt=\"logo\" style=\"width:620px; height:420px;\"></a> </div>\r\n");
      out.write("\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><img style=\"width:100%; height:100%;\" id=\"main_img\" src=\"https://storage.googleapis.com/cbmpress/uploads/sites/2/2017/07/%EC%98%A4%EB%A0%88%EA%B1%B4-%EB%A7%A5%EC%A3%BC-%EC%B6%95%EC%A0%9COregon-Brewers-Festival.png\" alt=\"메인엑박\"></a>\r\n");
      out.write("\t\t\t\t\t<br><br>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</section>\t\t\r\n");
      out.write("\t\t<!-- 지우면 안되는 태그입니다 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Beer</title>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<section id=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-5\">\r\n");
      out.write("\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Vitae tempor lorem</h2>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer-float\" >\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"social\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-facebook-f\" href=\"#\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-twitter\" href=\"#\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-dribbble\" href=\"#\"><span class=\"label\">Dribbble</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-tumblr\" href=\"#\"><span class=\"label\">Tumblr</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-linkedin-in\" href=\"#\"><span class=\"label\">LinkedIn</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer-float\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Address</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t92, Jebong-ro, Dong-gu<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\tGwangju<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\tRepublic of Korea\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer-float\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Mail</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href=\"#\">EpIntoEk@gmail.com</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Phone</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>(062)1004-1004</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t<!-- Copyright -->\r\n");
      out.write("\t\t\t\t\t<div id=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"links\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>&copy; Untitled. All rights reserved.</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div><!-- 지우면 안되는 태그입니다 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scripts -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/browser.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/util.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/beer/main.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      // /WEB-INF/beer/main.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/beer/main.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/beer/nav.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("cpath");
      // /WEB-INF/beer/nav.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/beer/nav.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/beer/login.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("cpath");
      // /WEB-INF/beer/login.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/beer/login.jsp(8,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }
}
