/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2022-09-05 09:13:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.beer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/aischool/Desktop/work_folder/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/beer/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/beer/footer.jsp", Long.valueOf(1662360207153L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1662076816000L));
    _jspx_dependants.put("/WEB-INF/beer/nav.jsp", Long.valueOf(1662343728989L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Beer</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\" />\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"homepage is-preload\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar idCheck = false;\r\n");
      out.write("\tvar pwCheck = false;\r\n");
      out.write("\tvar nameCheck = false;\r\n");
      out.write("\tvar genderCheck = false;\r\n");
      out.write("\tvar emailCheck = false;\r\n");
      out.write("\tvar birthdateCheck = false;\r\n");
      out.write("\tvar aromaCheck = false;\r\n");
      out.write("\tvar fromCheck = false;\r\n");
      out.write("\tvar tasteCheck = false;\r\n");
      out.write("\tfunction doubleCheck(){\r\n");
      out.write("\t\tvar inputId = $('#m_id').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/doubleCheck.pik',\r\n");
      out.write("\t\t\ttype: \"post\",\r\n");
      out.write("\t\t\tdata: {\"m_id\":inputId},\r\n");
      out.write("\t\t\tsuccess: function(count){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(count==0){\r\n");
      out.write("\t\t\t\t\t$(\"#idCheckMsg\").html(\"id는 3자리 ~ 9자리 사이로 입력해주세요\")\r\n");
      out.write("\t\t\t\t\t$(\"#m_id\").val(\"\");\r\n");
      out.write("\t\t\t\t}else if(count==1){\r\n");
      out.write("\t\t\t\t\t$(\"#idCheckMsg\").html(\"중복된 아이디가 있습니다. 다른 아이디로 입력해주세요.\")\r\n");
      out.write("\t\t\t\t\t$(\"#m_id\").val(\"\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"중복된 아이디가 없습니다!!!\");\r\n");
      out.write("\t\t\t\t\t$(\"#idCheckMsg\").html(\"\")\r\n");
      out.write("\t\t\t\t\tidCheck = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(){alert(\"id중복기능 에러\");}\r\n");
      out.write("\t\t})\r\n");
      out.write("// \t\t$(\"#checkTrue\").css(\"display\",\"inline\");\r\n");
      out.write("// \t\t$(\"#checkFalse\").css(\"display\",\"none\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction resetIdCheck(){\r\n");
      out.write("\t\tidCheck=false;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction resetPwCheck(){\r\n");
      out.write("\t\tCheck=false;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction doubleCheckFalse(){\r\n");
      out.write("\t\talert(\"중복확인을 먼저 해주세요.\")\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction checkPw(){\r\n");
      out.write("\t\tvar pw = $(\"#m_pw\").val();\r\n");
      out.write("\t\tvar pw2 = $(\"#m_pw1\").val();\r\n");
      out.write("\t\tvar sc = [\"!\",\"@\",\"#\",\"$\",\"%\"];\r\n");
      out.write("        var check_sc = 0;\r\n");
      out.write("        for(var i=0;i<sc.length;i++){\r\n");
      out.write("            if(pw.indexOf(sc[i]) != -1){\r\n");
      out.write("            \tcheck_sc = 1;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        if(pw.length < 6 || pw.length>16){\r\n");
      out.write("//             window.alert('비밀번호는 6글자 이상, 16글자 이하만 이용 가능합니다.');\r\n");
      out.write("            $(\"#pwCheckMsg\").text(\"비밀번호는 6글자 이상, 16글자 이하만 이용 가능합니다.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("        }\r\n");
      out.write("        if(check_sc == 0){\r\n");
      out.write("        \t$(\"#pwCheckMsg\").text(\"특수문자를 포함해주세요\");\r\n");
      out.write("        }else if(check_sc == 1){\r\n");
      out.write("        \t$(\"#pwCheckMsg\").text(\"\");\r\n");
      out.write("        }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction pwDoubleCheck(){\r\n");
      out.write("\t\tvar pw = $(\"#m_pw\").val();\r\n");
      out.write("\t\tvar pw2 = $(\"#m_pw1\").val();\r\n");
      out.write("\t\tif(pw != pw2){\r\n");
      out.write("\t\t\t$(\"#pwDoubleCheckMsg\").html(\"비밀번호가 일치하지 않습니다\");\r\n");
      out.write("\t\t\tpwCheck = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(pw == pw2){\r\n");
      out.write("\t\t\t$(\"#pwDoubleCheckMsg\").html(\"\");\r\n");
      out.write("\t\t\tpwCheck = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction checkName(){\r\n");
      out.write("\t\tif($(\"#m_name\").val() == \"\"){\r\n");
      out.write("\t\t\t$(\"#nameCheckMsg\").html(\"이름을 입력해주세요\");\r\n");
      out.write("\t\t\tnameCheck = false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#nameCheckMsg\").html(\"\");\r\n");
      out.write("\t\t\tnameCheck = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction checkGender(){\r\n");
      out.write("\t\tif($(\"#m_gender\").val()==\"-1\"){\r\n");
      out.write("\t\t\t$(\"#genderCheckMsg\").html(\"성별을 선택해주세요\");\r\n");
      out.write("\t\t\tgenderCheck = false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#genderCheckMsg\").html(\"\")\r\n");
      out.write("\t\t\tgenderCheck = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction checkBirthDate(){\r\n");
      out.write("\t\tif($(\"#m_birthdate\").val()==\"\"){\r\n");
      out.write("\t\t\tconsole.log($(\"#m_birthdate\").val()+'true')\r\n");
      out.write("\t\t\t$(\"#birthdateCheckMsg\").html(\"생년월일을 선택해주세요\");\r\n");
      out.write("\t\t\tbirthdateCheck=false;\r\n");
      out.write("\t\t\tconsole.log(birthdateCheck)\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tconsole.log($(\"#m_birthdate\").val()+'false')\r\n");
      out.write("\t\t\t$(\"#birthdateCheckMsg\").html(\"\");\r\n");
      out.write("\t\t\tbirthdateCheck = true;\r\n");
      out.write("\t\t\tconsole.log(birthdateCheck)\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction checkEmail(){\r\n");
      out.write("\r\n");
      out.write("\t\tvar email = $(\"#m_email\").val()\r\n");
      out.write("\t\tvar arrUrl=[\".co.kr\",\".com\",\".net\",\".or.kr\",\".go.kr\"]\r\n");
      out.write("\t\tvar emailForm1 = false;\r\n");
      out.write("\t\tvar emailForm2 = false;\r\n");
      out.write("\t\tif($(\"#m_email\").val()==\"\"){\r\n");
      out.write("\t\t\t$(\"#emailCheckMsg\").html(\"이메일을 입력해주세요\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#emailCheckMsg\").html(\"\");\r\n");
      out.write("\t\t\temailForm1 = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor(var i = 0; i<arrUrl.length;i++){\r\n");
      out.write("\t\t\tif(email.indexOf(arrUrl[i])>0){\r\n");
      out.write("\t\t\t\temailForm2 = true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(emailForm1 && emailForm2){\r\n");
      out.write("\t\t\temailCheck=true;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#emailCheckMsg\").html(\"이메일 형식을 맞춰주세요\");\r\n");
      out.write("\t\t\temailCheck=false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction checkAroma(){\r\n");
      out.write("\t\tif($(\"#beer_option1\").val()==\"-1\"){\r\n");
      out.write("\t\t\t$(\"#aromaCheckMsg\").html(\"좋아하는 향을 선택해주세요\");\r\n");
      out.write("\t\t\taromaCheck = false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#aromaCheckMsg\").html(\"\");\r\n");
      out.write("\t\t\taromaCheck = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction checkFrom(){\r\n");
      out.write("\t\tif($(\"#beer_option2\").val()==\"-1\"){\r\n");
      out.write("\t\t\t$(\"#fromCheckMsg\").html(\"좋아하는 원산지을 선택해주세요\");\r\n");
      out.write("\t\t\tfromCheck = false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#fromCheckMsg\").html(\"\");\r\n");
      out.write("\t\t\tfromCheck = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction checkTaste(){\r\n");
      out.write("\t\tif($(\"#beer_option3\").val()==\"-1\"){\r\n");
      out.write("\t\t\t$(\"#tasteCheckMsg\").html(\"좋아하는 맛을 선택해주세요\");\r\n");
      out.write("\t\t\ttasteCheck = false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#tasteCheckMsg\").html(\"\");\r\n");
      out.write("\t\t\ttasteCheck = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction registerSubmit(){\r\n");
      out.write("\t\tif(!idCheck){\r\n");
      out.write("\t\t\talert(\"id입력을 확인해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!pwCheck){\r\n");
      out.write("\t\t\talert(\"암호를 확인해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!nameCheck){\r\n");
      out.write("\t\t\talert(\"이름을 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!genderCheck){\r\n");
      out.write("\t\t\talert(\"성별을 선택해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!emailCheck){\r\n");
      out.write("\t\t\talert(\"이메일 주소를 확인해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!birthdateCheck){\r\n");
      out.write("\t\t\talert(\"생년월일을 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!aromaCheck){\r\n");
      out.write("\t\t\talert(\"선호하는 향을 선택해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!fromCheck){\r\n");
      out.write("\t\t\talert(\"선호하는 원산지를 선택해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!tasteCheck){\r\n");
      out.write("\t\t\talert(\"선호하는 맛을 선택해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\t\t<div id=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Header -->\r\n");
      out.write("\t\t\t<section id=\"header\">\r\n");
      out.write("\t\t\t\t\t<!-- Logo -->\r\n");
      out.write("\t\t\t\t\t<!-- Nav -->\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Beer</title>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\" />\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var loginID = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.m_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("        \r\n");
      out.write("         $(function(){\r\n");
      out.write("             if(loginID){\r\n");
      out.write("                 $(\"#loginMember\").css(\"display\",\"inline-block\");\r\n");
      out.write("             }else{\r\n");
      out.write("                 $(\"#loginMember\").css(\"display\",\"none\");\r\n");
      out.write("             }\r\n");
      out.write("         });\r\n");
      out.write("         $(document).ready(function(){      \r\n");
      out.write("                ");
String btnPath = request.getRequestURI().split("/")[4].split("\\.")[0];
                if(btnPath.indexOf("articleList")!=-1 || btnPath.indexOf("articleView")!=-1){
                
      out.write("$(\"#review_btn\").addClass(\"current\");  ");

                }else if(btnPath.indexOf("eventList")!=-1){
                
      out.write("$(\"#notice_btn\").addClass(\"current\");  ");

                }else if(btnPath.indexOf("myPage")!=-1){
                
      out.write("$(\"#loginMember\").addClass(\"current\"); ");

                }
      out.write("\r\n");
      out.write("            })  \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Logo -->\r\n");
      out.write("    <h1><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.pik\">Beer</a></h1>\r\n");
      out.write("<!-- Nav -->\r\n");
      out.write("    <nav id=\"nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li id=\"home_btn\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.pik\">Home</a></li>\r\n");
      out.write("            <li id=\"info_btn\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/beerRecommendForm.pik\">Beer Info</a></li>\r\n");
      out.write("            <li id=\"search_btn\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/beerSearchForm.pik\">Beer Search</a></li>\r\n");
      out.write("            <li id=\"review_btn\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/articleList.pik?page=1\">Review</a></li>\r\n");
      out.write("            <li id=\"notice_btn\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/eventList.pik\">Notice</a></li>\r\n");
      out.write("            <li id=\"loginMember\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage.pik\">My Page</a></li>\r\n");
      out.write("            \r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t</section><!-- 지우면 안되는 태그입니다 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Main -->\r\n");
      out.write("\t\t\t\t<section id=\"main\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Portfolio -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<header class=\"major\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2>회원가입</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form action=\"/beer/register.pik\" method=\"post\" onsubmit=\"return registerSubmit();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"token_sjoin\" name=\"token_sjoin\" value=\"6fnwb3fdYkQTX854\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"encPswd\" name=\"encPswd\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"encKey\" name=\"encKey\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"birthday\" name=\"birthday\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"joinMode\" name=\"joinMode\" value=\"unreal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"pbirthday\" name=\"pbirthday\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"ipinFlag\" name=\"ipinFlag\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"nid_kb2\" name=\"nid_kb2\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\" style=\"justify-content: center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div  style=\"width:50%\" class=\"col-4 col-6-medium col-12-small\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- 아이디 입력 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"join_title\"><label for=\"id\">아이디</label></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<section class=\"box\" style=\"padding:0; display: flex; margin-bottom:0\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"width: 76.5%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"m_id\" name=\"m_id\" class=\"int\" title=\"ID\" maxlength=\"20\" onchange=\"resetIdCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"button alt\" onclick=\"doubleCheck()\" value=\"중복확인\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"display:block; margin-bottom:2.5em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"idCheckMsg\" style=\"color:red;background-color:transparent !important;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"join_title\"><label for=\"password\">비밀번호</label></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<section class=\"box\" style=\"padding:0; margin-bottom:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" id=\"m_pw\" name=\"m_pw\" onchange=\"checkPw()\" class=\"int\" title=\"비밀번호 입력\" aria-describedby=\"pswd1Msg\" maxlength=\"20\" onchange=\"pwDoubleCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"display:block; margin-bottom:2.5em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"pwCheckMsg\" style=\"color:red;background-color:transparent !important;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- 비밀번호 확인 입력 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"join_title\"><label for=\"password1\">비밀번호 재확인</label></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<section class=\"box\" style=\"padding:0; margin-bottom:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" id=\"m_pw1\" name=\"m_pw1\" class=\"int\" title=\"비밀번호 재확인 입력\" aria-describedby=\"pswd2Blind\" maxlength=\"20\" onchange=\"pwDoubleCheck()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"display:block; margin-bottom:2.5em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"pwDoubleCheckMsg\" style=\"color:red;background-color:transparent !important;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- 이름 입력 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"join_title\"><label for=\"name\">이름</label></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<section class=\"box\" style=\"padding:0; margin-bottom:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"m_name\" onfocusout=\"checkName()\" name=\"m_name\" title=\"이름\" class=\"int\" maxlength=\"40\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"display:block; margin-bottom:2.5em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"nameCheckMsg\" style=\"color:red;background-color:transparent !important;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- 생년월일 입력 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"join_title\"><label for=\"yy\">생년월일</label></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<section class=\"box\" style=\"padding:0; margin-bottom:0; display: flex;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"bir_yy\" style=\"width: 33.3333%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"date\" id=\"m_birthdate\" name=\"m_birthdate\" onchange=\"checkBirthDate()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"display:block; margin-bottom:2.5em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"birthdateCheckMsg\" style=\"color:red;background-color:transparent !important;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- 성별 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"join_title\" ><label for=\"gender\">성별</label></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<section class=\"box\" style=\"padding:0; margin-bottom:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"m_gender\" name=\"m_gender\" class=\"sel\" aria-label=\"성별\" onchange=\"checkGender()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"-1\" selected>성별</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">남자</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\">여자</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"display:block; margin-bottom:2.5em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"genderCheckMsg\" style=\"color:red;background-color:transparent !important;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- 이메일 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"join_title\"><label for=\"email\">본인 확인 이메일<span class=\"terms_choice\"></span></label></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<section class=\"box\" style=\"padding:0; margin-bottom:0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" onchange=\"checkEmail()\" onfocusout=\"checkEmail()\" id=\"m_email\" name=\"m_email\" aria-label=\"선택입력\" class=\"int\" maxlength=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"display:block; margin-bottom:2.5em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"emailCheckMsg\" style=\"color:red; background-color:transparent !important;\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- 취향 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\" style=\"justify-content: center; margin-top:10px; !important\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div  style=\"width:50%\" class=\"col-4 col-6-medium col-12-small\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin:auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div style=\" margin-bottom:0;padding-top: 10px; padding-bottom:10px; display:inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 style=\"display:inline;\"> Aroma :  </h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"beer_aroma\" id=\"beer_option1\" class=\"beer_option_select\" onchange=\"checkAroma()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option selected value=\"-1\"> choose ▽  </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 1 >에일</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 2 >라거</option>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 3 >밀맥주</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 4 >필스너</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 5 >흑맥주</option>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 6 >기타</option>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"display:block; margin-bottom:2.5em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"aromaCheckMsg\" style=\"color:red;background-color:transparent !important;\">좋아하는 향을 선택해주세요</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin:auto; display:inline;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 style=\"display:inline;\"> From :  </h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"beer_from\" id=\"beer_option2\" class=\"beer_option_select\" onchange=\"checkFrom()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option selected value=\"-1\"> choose ▽  </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 1 >국내</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 2 >해외</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"display:block; margin-bottom:2.5em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"fromCheckMsg\" style=\"color:red;background-color:transparent !important;\">선호하는 원산지를 선택해주세요</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin:auto; padding-top: 10px; display:inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 style=\"display:inline;\"> Taste :  </h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"beer_taste\" id=\"beer_option3\" class=\"beer_option_select\" onchange=\"checkTaste()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option selected value=\"-1\"> choose ▽  </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 1 >Sweet</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 2 >Dry</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 3 >Soft</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 4 >Deep</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 5 >Bitter</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"display:block; margin-bottom:2.5em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"tasteCheckMsg\" style=\"color:red;background-color:transparent !important;\">좋아하는 맛을 선택해주세요</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"actions\" align=\"center\" style=\"margin-top: 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"checkTrue\" style=\"padding:12px 35px; margin-right: 10px; font-size:1.3em;\" type=\"submit\" class=\"button large\" value=\"회원 가입\">\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t\t\t<input id=\"checkFalse\" onclick=\"doubleCheckFalse()\" style=\"padding:12px 35px; margin-right: 10px; font-size:1.3em ;\" type=\"button\" class=\"button alt\" value=\"회원 가입\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input style=\"padding:12px 35px; margin-left: 10px; font-size:1.3em;\" type=\"reset\" class=\"button alt large\"  value=\"다시 입력\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Beer</title>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<section id=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-5\">\r\n");
      out.write("\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Vitae tempor lorem</h2>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer-float\" >\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"social\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-facebook-f\" href=\"#\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-twitter\" href=\"#\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-dribbble\" href=\"#\"><span class=\"label\">Dribbble</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-tumblr\" href=\"#\"><span class=\"label\">Tumblr</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-linkedin-in\" href=\"#\"><span class=\"label\">LinkedIn</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer-float\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Address</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t92, Jebong-ro, Dong-gu<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\tGwangju<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\tRepublic of Korea\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer-float\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Mail</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href=\"#\">EpIntoEk@gmail.com</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Phone</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>(062)1004-1004</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t<!-- Copyright -->\r\n");
      out.write("\t\t\t\t\t<div id=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"links\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>&copy; Untitled. All rights reserved.</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t</div> <!-- 지우면 안되는 태그입니다 -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Scripts -->\r\n");
      out.write("\t\t\t<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"assets/js/util.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/beer/register.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      // /WEB-INF/beer/register.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/beer/register.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/beer/nav.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("cpath");
      // /WEB-INF/beer/nav.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/beer/nav.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
