/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2022-09-06 07:35:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.beer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.*;
import kr.entity.pik.Paging;
import java.io.PrintWriter;
import org.apache.ibatis.reflection.SystemMetaObject;
import kr.entity.pik.Member;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/aischool/Desktop/work_folder/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/beer/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/beer/footer.jsp", Long.valueOf(1662360207153L));
    _jspx_dependants.put("/WEB-INF/beer/login.jsp", Long.valueOf(1662374292769L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1662076816000L));
    _jspx_dependants.put("/WEB-INF/beer/nav.jsp", Long.valueOf(1662373504685L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("org.apache.ibatis.reflection.SystemMetaObject");
    _jspx_imports_classes.add("kr.entity.pik.Paging");
    _jspx_imports_classes.add("kr.entity.pik.Member");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
	
	Calendar cal = Calendar.getInstance();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Beer</title>\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\" />\r\n");
      out.write("\t<style type=\"text/css\">\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t.beer_search_head_td{\r\n");
      out.write("\t\t\t\t\twidth: 400px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\ttr.beer_search_tr > td { padding : 20px 0px 20px 0px; margin : 20px 0px 20px 0px; text-align: center; }\t\r\n");
      out.write("\t\t\t\ttr.beer_search_tr:hover { background-color: beige; }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t#info_right_btn{\r\n");
      out.write("\t\t\t\t\tposition:relative;\r\n");
      out.write("\t\t\t\t\tleft:585px;\r\n");
      out.write("\t\t\t\t\t/* visibility : hidden; */\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t#info_left_btn{\r\n");
      out.write("\t\t\t\t\tposition:relative;\r\n");
      out.write("\t\t\t\t\t/* visibility : hidden; */\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t#go_btn{\r\n");
      out.write("\t\t\t\t\tposition:relative;\t\r\n");
      out.write("\t\t\t\t\tleft:610px;\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t.search_div{\r\n");
      out.write("\t\t\t\t\tmargin: auto;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tdisplay: flex; \r\n");
      out.write("\t\t\t\t\tjustify-content:center;\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\ttext-align:center; \r\n");
      out.write("\t\t\t\t\toverflow:hidden; \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tborder: 3px solid gold; \r\n");
      out.write("\t\t\t\t\tborder-radius: 50%; \r\n");
      out.write("\t\t\t\t\t-moz-border-radius: 50%; \r\n");
      out.write("\t\t\t\t\t-khtml-border-radius: 50%; \r\n");
      out.write("\t\t\t\t\t-webkit-border-radius: 50%; \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\twidth:500px; \r\n");
      out.write("\t\t\t\t\theight:500px;\r\n");
      out.write("\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t.search_img{\t\t\t\t\r\n");
      out.write("\t\t\t\t\tobject-fit: cover; \r\n");
      out.write("\t\t\t\t\tmax-width: 100%; \r\n");
      out.write("\t\t\t\t\theight: auto;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t.count_div{\r\n");
      out.write("\t\t\t\t\tposition:relative; \r\n");
      out.write("\t\t\t\t\tleft:310px; \r\n");
      out.write("\t\t\t\t\ttop:-20px;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tdisplay: flex; \r\n");
      out.write("\t\t\t\t\tjustify-content:center;\t\r\n");
      out.write("\t\t\t\t\ttext-align:center; \r\n");
      out.write("\t\t\t\t\toverflow:hidden; \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tbackground-color:white; \r\n");
      out.write("\t\t\t\t\tborder: 3px solid beige; \r\n");
      out.write("\t\t\t\t\tborder-radius: 50%; \r\n");
      out.write("\t\t\t\t\t-moz-border-radius: 50%; \r\n");
      out.write("\t\t\t\t\t-khtml-border-radius: 50%; \r\n");
      out.write("\t\t\t\t\t-webkit-border-radius: 50%; \r\n");
      out.write("\t\t\t\t\twidth:50px; height:50px;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t#buttion2_div{\r\n");
      out.write("\t\t\t\t\tposition:absolute;\r\n");
      out.write("\t\t\t\t\ttop: 55%;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t#buttion1_div{\r\n");
      out.write("\t\t\t\t\tposition:absolute;\r\n");
      out.write("\t\t\t\t\ttop: 15.5%;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t.beer_option_select{\r\n");
      out.write("\t\t\t\t\tall: unset;\r\n");
      out.write("\t\t\t\t\tbackground-color: beige;\r\n");
      out.write("\t\t\t\t\tcolor: black;\r\n");
      out.write("\t\t\t\t\tpadding: 5px 20px;\r\n");
      out.write("\t\t\t\t\tborder-radius: 10px;\r\n");
      out.write("\t\t\t\t\tcursor: pointer; \r\n");
      out.write("\t\t\t\t\tfont-weight:bold;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\t\r\n");
      out.write("\t\t$(document).ready(function(){  \t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#search_btn\").addClass(\"current\");\r\n");
      out.write("\t\t\tSide_load();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#beer_name\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction Side_load() {\r\n");
      out.write("\t\t\tconsole.log(\"side_list\");\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/beerSideList.pik\",\r\n");
      out.write("\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\tsuccess:function (data) {\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif (data != \"\"){\r\n");
      out.write("\t\t\t\t\t\tvar str1 = data.split('/')[0];\r\n");
      out.write("\t\t\t\t\t\tvar str2 = data.split('/')[1];\r\n");
      out.write("\t\t\t\t\t\tvar str3 = data.split('/')[2];\r\n");
      out.write("\t\t\t\t\t\t$(\"#before_recommend_beer1\").html('1. '+str1+' ');\r\n");
      out.write("\t\t\t\t\t\t$(\"#before_recommend_beer2\").html('2. '+str2+' ');\r\n");
      out.write("\t\t\t\t\t\t$(\"#before_recommend_beer3\").html('3. '+str3+' ');\r\n");
      out.write("\t\t\t\t\t}\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror:function(){ console.log(\"Admin account is not enough data for beer\")}\r\n");
      out.write("\t\t\t})\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction getInsert() {\t\t\t\r\n");
      out.write("\t\t\t$(\"#search_img\").css(\"display\", \"none\");\t\t\t\r\n");
      out.write("\t\t\tvar fdata = $(\"#bfrm\").serialize();\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl :  \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/beerSearchList.pik\",\r\n");
      out.write("    \t\t\ttype : \"post\",\r\n");
      out.write("    \t\t\tdata : fdata,   \r\n");
      out.write("    \t\t\tdataType : 'json',\r\n");
      out.write("    \t\t\tsuccess : viewList, //다시 리스트 호출\r\n");
      out.write("    \t\t\terror : function() {alert(\"error\");}\r\n");
      out.write("\t\t\t})\t\t\t\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(function (){\r\n");
      out.write("\t\t\t$(\"#go_btn\").click(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar str = $(\"#beer_name\").val();\t\r\n");
      out.write("\t\t\t\tvar op1 = $(\"#beer_option1\").val();\t\t\t\t\r\n");
      out.write("\t\t\t\tvar op2 = $(\"#beer_option2\").val();\r\n");
      out.write("\t\t\t\tvar op3 = $(\"#beer_option3\").val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif (str != \"\"){\r\n");
      out.write("\t\t\t\t\tgetInsert();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if (op1 != \"null\" && op2 != \"null\" && op3 != \"null\"){\r\n");
      out.write("\t\t\t\t\tgetInsert();\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"맥주의 이름 또는 취향 3가지를 입력하세요\");\r\n");
      out.write("\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar searchtf = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar index_max = 0;\r\n");
      out.write("\t\tfunction viewList(data) {\t\t\t\t\r\n");
      out.write("\t\t\tvar html=\"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (searchtf){\r\n");
      out.write("\t\t\t\t$(\"#beer_info\").empty();\r\n");
      out.write("\t\t\t\tindex_max = 0;\r\n");
      out.write("\t\t\t\tindex=0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.each(data,function(index,beer){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif (index == 0){\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"<div id='div_index_\"+index+\"' style='display:block;'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<div class='count_div'><h3 style='color:red; object-fit: cover; max-width: 100%; height: auto;'>\"+(index+1)+\"</h3>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"<div class='search_div' id='search_img_\"+index+\"'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<img class='search_img' src=\"+beer.BEER_SRC+\">\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"<section>\";\t\r\n");
      out.write("\t\t\t\t\t//table\r\n");
      out.write("\t\t\t\t\thtml += \"<table>\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//title\r\n");
      out.write("\t\t\t\t\thtml += \"<tr class='beer_search_tr'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td colspan='2' class='beer_search_head_td'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<h2 style='padding-top:20px;'>\"+beer.BEER_NAME+\"</h2>\";\t\r\n");
      out.write("\t\t\t\t\thtml += \"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t//1\r\n");
      out.write("\t\t\t\t\thtml += \"<tr class='beer_search_tr'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='beer_search_head_td'><h3>Beer From</h3></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<h4>\"+beer.FROM_SEQ+\"</h4>\";\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</td>\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t//2\r\n");
      out.write("\t\t\t\t\thtml += \"<tr class='beer_search_tr'>\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='beer_search_head_td'><h3>Beer Aroma</h3></td>\";\t\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\"; \r\n");
      out.write("\t\t\t\t\thtml += \"<h4>\"+beer.AROMA_SEQ+\"</h4>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\t\r\n");
      out.write("\t\t\t\t\t//3\r\n");
      out.write("\t\t\t\t\thtml += \"<tr class='beer_search_tr'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><h3>Beer Taste</h3></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\"; \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif (beer.TASTE_SEQ3 == null){\r\n");
      out.write("\t\t\t\t\t\thtml += \"<h4>\"+beer.TASTE_SEQ+\" / \"+beer.TASTE_SEQ2+\"</h4>\";\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\thtml += \"<h4>\"+beer.TASTE_SEQ+\" / \"+beer.TASTE_SEQ2+\" / \"+beer.TASTE_SEQ3+\"</h4>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</td>\";\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t//4\r\n");
      out.write("\t\t\t\t\thtml += \"<tr class='beer_search_tr'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='beer_search_head_td'><h3>Beer ABV</h3></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='beer_search_head_td'>\"; \r\n");
      out.write("\t\t\t\t\thtml += \"<h4>\"+beer.BEER_ABV+\"</h4>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</td>\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t//5\r\n");
      out.write("\t\t\t\t\thtml += \"<tr class='beer_search_tr'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='beer_search_head_td'><h3>Beer Country</h3></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\"; \r\n");
      out.write("\t\t\t\t\thtml += \"<h4>\"+beer.COUNTRY_CD+\"</h4>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</td>\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</table>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</section>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"<div id='div_index_\"+index+\"' style='display:none;'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<div class='count_div'><h3 style='color:red; object-fit: cover; max-width: 100%; height: auto;'>\"+(index+1)+\"</h3>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"<div class='search_div' id='search_img_\"+index+\"'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<img class='search_img' src=\"+beer.BEER_SRC+\">\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"<section>\";\t\r\n");
      out.write("\t\t\t\t\t//table\r\n");
      out.write("\t\t\t\t\thtml += \"<table>\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//title\r\n");
      out.write("\t\t\t\t\thtml += \"<tr class='beer_search_tr'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td colspan='2' class='beer_search_head_td'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<h2 style='padding-top:20px;'>\"+beer.BEER_NAME+\"</h2>\";\t\r\n");
      out.write("\t\t\t\t\thtml += \"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t//1\r\n");
      out.write("\t\t\t\t\thtml += \"<tr class='beer_search_tr'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='beer_search_head_td'><h3>Beer From</h3></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<h4>\"+beer.FROM_SEQ+\"</h4>\";\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</td>\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t//2\r\n");
      out.write("\t\t\t\t\thtml += \"<tr class='beer_search_tr'>\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='beer_search_head_td'><h3>Beer Aroma</h3></td>\";\t\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\"; \r\n");
      out.write("\t\t\t\t\thtml += \"<h4>\"+beer.AROMA_SEQ+\"</h4>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\t\r\n");
      out.write("\t\t\t\t\t//3\r\n");
      out.write("\t\t\t\t\thtml += \"<tr class='beer_search_tr'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><h3>Beer Taste</h3></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\"; \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif (beer.TASTE_SEQ3 == null){\r\n");
      out.write("\t\t\t\t\t\thtml += \"<h4>\"+beer.TASTE_SEQ+\" / \"+beer.TASTE_SEQ2+\"</h4>\";\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\thtml += \"<h4>\"+beer.TASTE_SEQ+\" / \"+beer.TASTE_SEQ2+\" / \"+beer.TASTE_SEQ3+\"</h4>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</td>\";\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t//4\r\n");
      out.write("\t\t\t\t\thtml += \"<tr class='beer_search_tr'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='beer_search_head_td'><h3>Beer ABV</h3></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='beer_search_head_td'>\"; \r\n");
      out.write("\t\t\t\t\thtml += \"<h4>\"+beer.BEER_ABV+\"</h4>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</td>\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t//5\r\n");
      out.write("\t\t\t\t\thtml += \"<tr class='beer_search_tr'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='beer_search_head_td'><h3>Beer Country</h3></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\"; \r\n");
      out.write("\t\t\t\t\thtml += \"<h4>\"+beer.COUNTRY_CD+\"</h4>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</td>\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</table>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</section>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</div>\";\r\n");
      out.write("\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tindex_max = index;\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#beer_info\").html(html);\r\n");
      out.write("\t\t\tsearchtf = true;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#info_right_btn\").css(\"visibility\", \"visible\");\r\n");
      out.write("\t\t\t$(\"#info_left_btn\").css(\"visibility\", \"visible\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar index = 0;\r\n");
      out.write("\t\tfunction goleft(){\r\n");
      out.write("\t\t\tif (index > 0){\r\n");
      out.write("\t\t\t\t$(\"#div_index_\"+index).css('display','none');\r\n");
      out.write("\t\t\t\tindex-=1;\r\n");
      out.write("\t\t\t\t$(\"#div_index_\"+index).css('display','block');\t\t\t\t\r\n");
      out.write("\t\t\t} else if (index==0){\r\n");
      out.write("\t\t\t\t$(\"#div_index_\"+index).css('display','none');\r\n");
      out.write("\t\t\t\tindex = index_max;\r\n");
      out.write("\t\t\t\t$(\"#div_index_\"+index).css('display','block');\t\t\t\t\r\n");
      out.write("\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\tfunction goright(){\r\n");
      out.write("\t\t\tif (index+1 > index_max){\r\n");
      out.write("\t\t\t\t$(\"#div_index_\"+index).css('display','none');\r\n");
      out.write("\t\t\t\tindex = 0;\r\n");
      out.write("\t\t\t\t$(\"#div_index_\"+index).css('display','block');\t\t\t\t\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#div_index_\"+index).css('display','none');\r\n");
      out.write("\t\t\t\tindex+=1;\r\n");
      out.write("\t\t\t\t$(\"#div_index_\"+index).css('display','block');\t\t\t\t\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body class=\"left-sidebar is-preload\">\r\n");
      out.write("\t\t<div id=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Header -->\r\n");
      out.write("\t\t\t\t<section id=\"header\" style=\"padding-top: 0; padding-bottom: 0;\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- Nav -->\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Beer</title>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\" />\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var loginID = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo.m_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("        \r\n");
      out.write("         $(function(){\r\n");
      out.write("             if(loginID){\r\n");
      out.write("                 $(\"#loginMember\").css(\"display\",\"inline-block\");\r\n");
      out.write("             }else{\r\n");
      out.write("                 $(\"#loginMember\").css(\"display\",\"none\");\r\n");
      out.write("             }\r\n");
      out.write("         });\r\n");
      out.write("         $(document).ready(function(){      \r\n");
      out.write("                ");
String btnPath = request.getRequestURI().split("/")[4].split("\\.")[0];
                if(btnPath.indexOf("articleList")!=-1 || btnPath.indexOf("articleView")!=-1){
                
      out.write("$(\"#review_btn\").addClass(\"current\");  ");

                }else if(btnPath.indexOf("eventList")!=-1){
                
      out.write("$(\"#notice_btn\").addClass(\"current\");  ");

                }else if(btnPath.indexOf("myPage")!=-1){
                
      out.write("$(\"#loginMember\").addClass(\"current\"); ");

                }
      out.write("\r\n");
      out.write("            })  \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    .a-hover:hover {\r\n");
      out.write("    \tbackground-color: rgba(255, 217, 0, 0.232) !important;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Logo -->\r\n");
      out.write("<div style=\"background-color:#252122; height:200px;\">\r\n");
      out.write("    <h1 style=\"padding-top: 45px\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.pik\" style=\"color:gold\">Beer</a></h1>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!-- Nav -->\r\n");
      out.write("    <nav id=\"nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li id=\"home_btn\"><a class=\"a-hover\" style=\"color:#f7f7f7;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.pik\">Home</a></li>\r\n");
      out.write("            <li id=\"info_btn\"><a class=\"a-hover\" style=\"color:#f7f7f7;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/beerRecommendForm.pik\">Beer Info</a></li>\r\n");
      out.write("            <li id=\"search_btn\"><a class=\"a-hover\" style=\"color:#f7f7f7;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/beerSearchForm.pik\">Beer Search</a></li>\r\n");
      out.write("            <li id=\"review_btn\"><a class=\"a-hover\" style=\"color:#f7f7f7;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/articleList.pik?page=1\">Review</a></li>\r\n");
      out.write("            <li id=\"notice_btn\"><a class=\"a-hover\" style=\"color:#f7f7f7;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/eventList.pik\">Notice</a></li>\r\n");
      out.write("            <li id=\"loginMember\"><a class=\"a-hover\" style=\"color:#f7f7f7;\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPage.pik\">My Page</a></li>\r\n");
      out.write("            \r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Beer</title>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\"\r\n");
      out.write("\t\tcontent=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\" />\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t\t.popup-wrap{\r\n");
      out.write("\t\t\t\tbackground-color:rgba(0,0,0,.3);\r\n");
      out.write("\t\t\t\tdisplay: flex;\r\n");
      out.write("\t\t\t\tflex-direction: column;\r\n");
      out.write("\t\t\t\tjustify-content:center;\r\n");
      out.write("\t\t\t\talign-items:center;\r\n");
      out.write("\t\t\t\tposition:fixed;\r\n");
      out.write("\t\t\t\ttop:0;\r\n");
      out.write("\t\t\t\tleft:0;\r\n");
      out.write("\t\t\t\tright:0;\r\n");
      out.write("\t\t\t\tbottom:0;\r\n");
      out.write("\t\t\t\tz-index: 2;\r\n");
      out.write("\t\t\t\tdisplay:none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tif (!\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mvo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"){\r\n");
      out.write("\t\t\t$(\"#logInBtn\").css(\"display\",\"flex\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#logOutBtn\").css(\"display\",\"flex\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"homepage is-preload\">\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t");
 String reqPath = request.getRequestURI().split("/")[4].split("\\.")[0]+".pik";
		if(reqPath.indexOf("articleList")!=-1){
			reqPath+="?page=1";
		}else if(reqPath.indexOf("main")!=-1){
			reqPath="index.pik";
		}else if(reqPath.indexOf("info")!=-1){
			reqPath="beerRecommendForm.pik";
		}else if(reqPath.indexOf("search")!=-1){
			reqPath="beerSearchForm.pik";
		}else if(reqPath.indexOf("articleView")!=-1){
			String b_seq = request.getParameter("b_seq");
			reqPath+="?b_seq="+b_seq;
		}else if(reqPath.indexOf("myPage") != -1) {
			reqPath="index.pik";
		}
		
		
      out.write("\r\n");
      out.write("\t\tfunction open_popup(){\r\n");
      out.write("\t\t\tvar log_popup = document.getElementById(\"popup\")\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\tlog_popup.style.display=\"flex\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction log_out(){\r\n");
      out.write("\t\t\t if (confirm(\"정말 로그아웃 하시겠습니까?\") == true){\r\n");
      out.write("\t\t\t     location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout.pik?reqPath=");
      out.print(reqPath);
      out.write("\"\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t }else{\r\n");
      out.write("\t\t\t     return false;\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction close_popup(){\r\n");
      out.write("\t\t\tvar log_popup = document.getElementById(\"popup\")\r\n");
      out.write("\t\t\tlog_popup.style.display=\"none\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction login_submit(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar fData= $(\"#loginForm\").serialize();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.pik\",\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdata : fData,\r\n");
      out.write("\t\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\t\tlet data = $.trim(result)\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(data===\"aa\"){\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\tgoMain();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#failMsg\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(){alert(\"error\");} \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction goMain(){\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"+\"");
      out.print(reqPath);
      out.write("\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"logInBtn\" style=\"display:none; position: absolute; top: 5%; right: 2%;z-index: 2;  \">\r\n");
      out.write("\t\t<button onclick=\"open_popup()\" >LogIn</button>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"logOutBtn\" style=\"display:none; position: absolute; top: 5%; right: 2%;z-index: 2;\">\r\n");
      out.write("\t\t<button class=\"alt\" style=\"border:solid 1px #F2CB05; background-color: none; color:#F2CB05 !important;\" onclick=\"log_out()\">LogOut</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"popup\" class=\"popup-wrap\" style=\"width: 100%;height: 100%;\">\r\n");
      out.write("\t\t<div style=\"width: 450px;height: auto; background-color: #fff; border-radius: 15px 15px 15px 15px;\">\r\n");
      out.write("\t\t\t<div style=\"width: 100%;height: auto;background-color: #D52349;padding: 15px;border-radius: 15px 15px 0 0;\">\r\n");
      out.write("\t\t\t\t<div style=\"margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"color: white; margin-top: 10px;\">로그인</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"width: 100%;height: auto;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form id=\"loginForm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\" style=\"justify-content: center;height: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-4 col-6-medium col-12-small \" style=\"width: 85%; margin-top:20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 아이디 입력 -->\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"join_title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"m_id\">ID</label>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"padding: 0; display: flex;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"m_id\" name=\"m_id\" class=\"int\" title=\"ID\" placeholder=\"아이디를 입력하세요\" maxlength=\"20\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 비밀번호 입력 -->\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"join_title\" style=\"margin-top: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"m_pw\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box\" style=\"padding: 0; border-color: #fff;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" id=\"m_pw\" name=\"m_pw\" class=\"int\" placeholder=\"비밀번호를 입력하세요\" title=\"비밀번호 입력\" aria-describedby=\"pswd1Msg\" maxlength=\"20\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"failMsg\" class=\"box\" style=\"display:none;margin-top:10px;padding: 0 0 0 0; border-color: #fff;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"color:red; font : bold;\">아이디와 비밀번호를 확인하세요</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"box\" style=\"margin-top:10px;padding: 0 0 0 0; border-color: #fff;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/registerForm.pik\" style=\"color:blue; text-decoration-line: none !important; color: #5D5D5D;\">아직 회원이 아니시라면? 회원가입</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input hidden value=\"");
      out.print(reqPath);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"actions\"  style=\"margin-top: 25px; width: 100%;height: 20%;\">\r\n");
      out.write("\t\t\t\t\t\t<input style=\" font-size: 1.3em;width: 50%;height: 100%;margin: 0;float: left;border-radius: 0 0 0 15px;\"\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"button\" onclick=\"login_submit()\" class=\"button\" value=\"로그인\">\r\n");
      out.write("\t\t\t\t\t\t<input style=\" font-size: 1.3em;width: 50%;height: 100%;margin:0;float: right;border-radius: 0 0 15px 0;\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"button\" onclick=\"close_popup()\" class=\"button alt\" value=\"취소\"id=\"login-cancel\">\r\n");
      out.write("\t\t\t\t\t\t<input style=\"clear: both;\" hidden>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Scripts -->\r\n");
      out.write("\t<script type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/util.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Main -->\r\n");
      out.write("\t\t\t\t<section id=\"main\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-4 col-12-medium\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Sidebar -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<section class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>Before Recommend Beer</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p> ");
      out.print( cal.get(Calendar.YEAR) );
      out.write("년\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    ");
      out.print( cal.get(Calendar.MONTH) + 1);
      out.write("월\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    ");
      out.print( cal.get(Calendar.DATE) );
      out.write("일 </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"divided\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href='#' id=\"before_recommend_beer1\" style=\"text-decoration-line: none !important;\">오늘 기분은 어떠세요?</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href='#' id=\"before_recommend_beer2\" style=\"text-decoration-line: none !important;\">힘들지는 않았나요?</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href='#' id=\"before_recommend_beer3\" style=\"text-decoration-line: none !important;\">색 다른 맥주를 원하세요?</a></li>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-8 col-12-medium imp-medium\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"buttion2_div\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button id=\"info_left_btn\" onclick=\"goleft()\">◀</button>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button id=\"info_right_btn\" onclick=\"goright()\">▶</button>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"buttion1_div\">\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button id=\"go_btn\">Search!</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Content -->\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"box post\" style=\"background-color:white;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!--<a href=\"#\" class=\"image featured\"><img src=\"images/pic01.jpg\" alt=\"\" /></a>-->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<form id=\"bfrm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"margin:auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p style=\"display:inline; font-size:40px; font-weight: bold;\"> Name : </p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input style=\"all:unset; background-color: beige; color: black;padding: 5px 20px;border-radius: 10px;cursor: pointer; font-weight:bold; width:60%\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"beer_name\" id=\"beer_name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin:auto; padding-top: 10px; padding-bottom:10px; display:inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 style=\"display:inline;\"> Aroma :  </h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"beer_aroma\" id=\"beer_option1\" class=\"beer_option_select\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option selected value=\"null\"> choose ▽  </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 1 >에일</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 2 >라거</option>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 3 >밀맥주</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 4 >필스너</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 5 >흑맥주</option>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 6 >기타</option>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div><span>&nbsp</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin:auto; display:inline;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 style=\"display:inline;\"> From :  </h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"beer_from\" id=\"beer_option2\" class=\"beer_option_select\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option selected value=\"null\"> choose ▽  </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 1 >국내</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 2 >해외</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div><span>&nbsp</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin:auto; padding-top: 10px; display:inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h3 style=\"display:inline;\"> Taste :  </h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"beer_taste\" id=\"beer_option3\" class=\"beer_option_select\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option selected value=\"null\"> choose ▽  </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 1 >Sweet</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 2 >Dry</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 3 >Soft</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 4 >Deep</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= 5 >Bitter</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div><br><br>\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"search_img\" style=\"margin:auto; background-image:url(https://t1.daumcdn.net/cfile/tistory/2508675051FDB0B02D);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tborder: 3px solid gold; border-radius: 50%; -moz-border-radius: 50%; -khtml-border-radius: 50%; -webkit-border-radius: 50%; width:600px; height:600px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"beer_info\">\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br><h2 id=\"wuw\" style=\"margin:auto; text-align: center;\"> What U want? </h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Footer -->\r\n");
      out.write("\t\t\t\t<section id=\"footer\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Beer</title>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Footer -->\r\n");
      out.write("\t<section id=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-5\">\r\n");
      out.write("\t\t\t\t\t<section>\r\n");
      out.write("\t\t\t\t\t\t<header>\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Vitae tempor lorem</h2>\r\n");
      out.write("\t\t\t\t\t\t</header>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer-float\" >\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"social\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-facebook-f\" href=\"#\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-twitter\" href=\"#\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-dribbble\" href=\"#\"><span class=\"label\">Dribbble</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-tumblr\" href=\"#\"><span class=\"label\">Tumblr</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"icon brands fa-linkedin-in\" href=\"#\"><span class=\"label\">LinkedIn</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer-float\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Address</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t92, Jebong-ro, Dong-gu<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\tGwangju<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\tRepublic of Korea\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"footer-float\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Mail</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><a href=\"#\">EpIntoEk@gmail.com</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Phone</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>(062)1004-1004</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t<!-- Copyright -->\r\n");
      out.write("\t\t\t\t\t<div id=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"links\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>&copy; Untitled. All rights reserved.</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Scripts -->\r\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/browser.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/util.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/beer/search.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("cpath");
      // /WEB-INF/beer/search.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/beer/search.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/beer/nav.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("cpath");
      // /WEB-INF/beer/nav.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/beer/nav.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/beer/login.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("cpath");
      // /WEB-INF/beer/login.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/beer/login.jsp(8,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }
}
